### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by yrsurya** [some-natalie/ghas-to-csv#12]
Traceback (most recent call last):
  File "/app/main.py", line 77, in <module>
    cs_list = code_scanning.list_code_scanning_alerts(
AttributeError: module 'src.code_scanning' has no attribute 'list_code_scanning_alerts'. Did you mean: 'list_org_code_scanning_alerts'?

Seeing following issues while trying to use this , Thanks for getting this actions though very useful

**Comment by yrsurya** [comment]
@some-natalie  Tagging for visibilty , Really appreciate if get any assistance on this issue please

**Comment by some-natalie** [comment]
Hey @yrsurya, can you try `v0.4.0`?  I think that's fixed by #7 that was merged but untagged.

**Comment by yrsurya** [comment]
Run some-natalie/ghas-to-csv@v0.4.0
/usr/bin/docker run --name cd98fb5997da1b962[4](secret-scanning-reports/runs/7296955161?check_suite_focus=true#step:6:5)d92bd003[5](/secret-scanning-reports/runs/7296955161?check_suite_focus=true#step:6:6)558adb883f_d2e112 --label 4cd98f --workdir /github/workspace --rm -e GITHUB_PAT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/secret-scanning-reports/secret-scanning-reports":"/github/workspace" 4cd98f:b5997da1b9624d92bd0035558adb883f
Traceback (most recent call last):
  File "/app/main.py", line 80, in <module>
    code_scanning.write_repo_cs_list(cs_list)
  File "/app/src/code_scanning.py", line [8](secret-scanning-reports/runs/7296955161?check_suite_focus=true#step:6:9)1, in write_repo_cs_list
    if cs["state"] == "open":
TypeError: string indices must be integers

**Comment by yrsurya** [comment]
@some-natalie  Any update on above error , Please let me know if need more inforamation

**Comment by some-natalie** [comment]
Hey @yrsurya - the cryptic-ish error means your PAT either is invalid or has the wrong scope needed to do.  I haven't yet had the time to improve some of the error handling to give more/better info on why it failed, but the work is defined in #9 if you care to take a stab at it. ❤️ 

Here's what this looks like when running on the same repository that it is defined in:

```yaml
    steps:
      - name: CSV export
        uses: some-natalie/ghas-to-csv@main
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
```

**Comment by yrsurya** [comment]
I am sure provided correct PAT keys which had admin access to whole org , do we need to provide org details somewhere while pulling org wide secrets?

**Comment by some-natalie** [comment]
Hey @yrsurya , here's what it looks like for org-wide:

```yaml
      - name: CSV export
        uses: some-natalie/ghas-to-csv@main
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: "org-name-goes-here"
```
